- gradle/libs.versions.toml
- integration-test/build.gradle.kts
- komapper-ext-slf4j/build.gradle.kts
- komapper-ext-spring-boot-autoconfigure/build.gradle.kts
- komapper-ext-sqlcommenter/build.gradle.kts
- komapper-jdbc-h2/build.gradle.kts
- komapper-jdbc-mysql/build.gradle.kts
- komapper-jdbc-postgresql/build.gradle.kts
- komapper-processor/build.gradle.kts
- komapper-starter/build.gradle.kts
Because renovate does not seem to support Gradle's version catalog currently.
> Manage only spring's libraries in Gradle version catalog.

- komapper-codegen/src/main/kotlin/org/komapper/codegen/CodeGenerator.kt
- komapper-codegen/src/test/kotlin/org/komapper/codegen/CodeGeneratorTest.kt
Because some code formatters may refuse to import wildcards.
> Explicitly generate import statements.

- komapper-jdbc/src/main/kotlin/org/komapper/jdbc/JdbcExecutor.kt
- komapper-jdbc/src/main/kotlin/org/komapper/jdbc/JdbcSession.kt
- komapper-quarkus-jdbc/src/main/kotlin/org/komapper/quarkus/jdbc/JtaTransactionOperator.kt
- komapper-quarkus-jdbc/src/main/kotlin/org/komapper/quarkus/jdbc/JtaTransactionSession.kt
- komapper-r2dbc/src/main/kotlin/org/komapper/r2dbc/R2dbcExecutor.kt
- komapper-r2dbc/src/main/kotlin/org/komapper/r2dbc/R2dbcSession.kt
- komapper-spring-jdbc/build.gradle.kts
- komapper-spring-jdbc/src/main/kotlin/org/komapper/spring/jdbc/PlatformTransactionOperator.kt
- komapper-spring-jdbc/src/main/kotlin/org/komapper/spring/jdbc/PlatformTransactionSession.kt
- komapper-spring-jdbc/src/test/kotlin/org/komapper/spring/jdbc/Address.kt
- komapper-spring-jdbc/src/test/kotlin/org/komapper/spring/jdbc/PlatformTransactionOperatorTest.kt
- komapper-spring-r2dbc/build.gradle.kts
- komapper-spring-r2dbc/src/main/kotlin/org/komapper/spring/r2dbc/Null.kt
- komapper-spring-r2dbc/src/main/kotlin/org/komapper/spring/r2dbc/ReactiveCoroutineTransactionOperator.kt
- komapper-spring-r2dbc/src/main/kotlin/org/komapper/spring/r2dbc/ReactiveFlowTransactionOperator.kt
- komapper-spring-r2dbc/src/main/kotlin/org/komapper/spring/r2dbc/ReactiveTransactionSession.kt
- komapper-spring-r2dbc/src/test/kotlin/org/komapper/spring/r2dbc/Address.kt
- komapper-spring-r2dbc/src/test/kotlin/org/komapper/spring/r2dbc/ReactiveCoroutineTransactionOperatorTest.kt
- komapper-spring-r2dbc/src/test/kotlin/org/komapper/spring/r2dbc/ReactiveFlowTransactionOperatorTest.kt
- komapper-tx-jdbc/build.gradle.kts
- komapper-tx-jdbc/src/main/kotlin/org/komapper/tx/jdbc/JdbcTransactionOperator.kt
- komapper-tx-jdbc/src/main/kotlin/org/komapper/tx/jdbc/JdbcTransactionSession.kt
- komapper-tx-jdbc/src/test/kotlin/org/komapper/tx/jdbc/Address.kt
- komapper-tx-jdbc/src/test/kotlin/org/komapper/tx/jdbc/JdbcTransactionOperatorTest.kt
- komapper-tx-r2dbc/build.gradle.kts
- komapper-tx-r2dbc/src/main/kotlin/org/komapper/tx/r2dbc/R2dbcTransactionSession.kt
- komapper-tx-r2dbc/src/test/kotlin/org/komapper/tx/r2dbc/Address.kt
- komapper-tx-r2dbc/src/test/kotlin/org/komapper/tx/r2dbc/R2dbcFlowTransactionOperatorTest.kt
The following transaction operators should have the same behavior:
- JdbcTransactionOperator
- PlatformTransactionOperator
- JtaTransactionOperator
- R2dbcCoroutineTransactionOperator
- R2dbcFlowTransactionOperator
- ReactiveCoroutineTransactionOperator
- ReactiveFlowTransactionOperator
> Fix bugs in programmatic transaction management

- example-spring-boot-r2dbc/build.gradle.kts
- example-spring-boot-r2dbc/src/main/kotlin/example/spring/boot/r2dbc/WebConfig.kt
Because sqlcommenter depends on Web MVC.
> Remove sqlcommenter dependency from the WebFlux example project.

- integration-test-core/src/main/kotlin/integration/core/entities_dataType.kt
- integration-test-jdbc/src/main/kotlin/integration/jdbc/UserIntType.kt
- integration-test-jdbc/src/main/kotlin/integration/jdbc/UserStringType.kt
- integration-test-jdbc/src/main/resources/META-INF/services/org.komapper.jdbc.spi.JdbcUserDataType
- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcDataTypeTest.kt
- integration-test-r2dbc/src/main/kotlin/integration/r2dbc/UserIntType.kt
- integration-test-r2dbc/src/main/kotlin/integration/r2dbc/UserStringType.kt
- integration-test-r2dbc/src/main/resources/META-INF/services/org.komapper.r2dbc.spi.R2dbcUserDataType
- integration-test-r2dbc/src/test/kotlin/integration/r2dbc/R2dbcDataTypeTest.kt
- komapper-jdbc/src/main/kotlin/org/komapper/jdbc/JdbcDataType.kt
- komapper-jdbc/src/main/kotlin/org/komapper/jdbc/JdbcDataTypeProviders.kt
- komapper-jdbc/src/main/kotlin/org/komapper/jdbc/JdbcUserDataTypes.kt
- komapper-jdbc/src/main/kotlin/org/komapper/jdbc/spi/JdbcUserDataType.kt
- komapper-quarkus-jdbc-deployment/src/main/java/org/komapper/quarkus/jdbc/deployment/KomapperProcessor.java
- komapper-r2dbc/src/main/kotlin/org/komapper/r2dbc/R2dbcDataType.kt
- komapper-r2dbc/src/main/kotlin/org/komapper/r2dbc/R2dbcDataTypeProviders.kt
- komapper-r2dbc/src/main/kotlin/org/komapper/r2dbc/R2dbcUserDataTypes.kt
- komapper-r2dbc/src/main/kotlin/org/komapper/r2dbc/spi/R2dbcUserDataType.kt
The following shows how to use user-defined data classes as Entity property classes in JDBC access.
UserString.kt
```kotlin
data class UserString(val value: String)
```
UserStringType.kt
```kotlin
class UserStringType : JdbcUserDataType<UserString> {
override val name: String = "varchar(100)"
override val klass: KClass<UserString> = UserString::class
override val jdbcType: JDBCType = JDBCType.VARCHAR
override fun getValue(rs: ResultSet, index: Int): UserString? {
return rs.getString(index)?.let { UserString(it) }
}
override fun getValue(rs: ResultSet, columnLabel: String): UserString? {
return rs.getString(columnLabel)?.let { UserString(it) }
}
override fun setValue(ps: PreparedStatement, index: Int, value: UserString) {
ps.setString(index, value.value)
}
override fun toString(value: …
```
> Support for registering user-defined data types

- integration-test-core/src/main/kotlin/integration/core/entities_unit.kt
- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcUnitTest.kt
- komapper-annotation/src/main/kotlin/org/komapper/annotation/DefaultUnit.kt
- komapper-annotation/src/main/kotlin/org/komapper/annotation/annotations.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/EntityAnalyzer.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/EntityDefinitionSourceResolver.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/EntityMetamodelStubGenerator.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/EntityModel.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/EntityProcessor.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/Symbols.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/data.kt
- komapper-processor/src/test/kotlin/org/komapper/processor/EntityProcessorErrorTest.kt
This PR allows you to get metamodels from objects other than `org.komapper.core.dsl.Meta`.
Define:
```kotlin
// define your own metamodel providers
object Db1
object Db2
// define your entity using the above provider
@KomapperEntity(unit = Db1::class)
data class Cat(
@KomapperId
val id: Int,
val name: String
)
// define your entity using the above provider
@KomapperEntity(unit = Db2::class)
data class Dog(
@KomapperId
val id: Int,
val name: String
)
```
Use:
```kotlin
// get metamodels from the providers
val c = Db1.cat
val d = Db2.dog
```
See also https://slack-chats.kotlinlang.org/t/8022187/hi-is-there-support-for-having-different-meta-objects-for-mu
> Support to change metamodel provider class with annotation

- integration-test-core/src/main/kotlin/integration/core/entities_virtual.kt
- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcSchemaTest.kt
- komapper-annotation/src/main/kotlin/org/komapper/annotation/annotations.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/builder/SchemaStatementBuilder.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/metamodel/EntityMetamodel.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/EntityDefFactory.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/EntityFactory.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/EntityMetamodelGenerator.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/data.kt
By setting the `virtual` property to `true`, we can treat tables with no primary key as entities.
Define a linker entity that has virtual IDs:
```kotlin
data class Belonging(
@KomapperId(virtual = true) val employeeId: Int,
@KomapperId(virtual = true) val departmentId: Int
)
```
`QueryDsl.create` does not generate primary keys for virtual IDs:
```kotlin
db.runQuery {
// create table if not exists belonging (employee_id integer not null, department_id integer not null)
QueryDsl.create(Meta.belonging)
}
```
In other operations, virtual IDs are treated like normal IDs:
```kotlin
db.runQuery {
// delete from belonging as t0_ where t0_.employee_id = 1 and t0_.department_id = 1
QueryDsl.delete(Meta.belonging).single(Belonging(1,1))
}
```
> Add the `virtual` property to `@KomapperId` and `@KomapperEmbeddedId` 

- komapper-r2dbc/src/main/kotlin/org/komapper/r2dbc/R2dbcDialects.kt
- komapper-r2dbc/src/test/kotlin/org/komapper/r2dbc/R2dbcDialectsTest.kt
See https://github.com/r2dbc/r2dbc-pool/blob/v1.0.0.RELEASE/src/main/java/io/r2dbc/pool/PoolingConnectionFactoryProvider.java#L176-L186
If the PROTOCOL option contains a colon, the value before the colon means a driver.
> Support for r2dbc-pool's PROTOCOL option specification

- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcTemplateTest.kt
- integration-test-r2dbc/src/test/kotlin/integration/r2dbc/R2dbcTemplateTest.kt
- komapper-jdbc/src/main/kotlin/org/komapper/jdbc/JdbcDataOperator.kt
- komapper-r2dbc/src/main/kotlin/org/komapper/r2dbc/R2dbcDataOperator.kt
- komapper-template/src/main/kotlin/org/komapper/template/expression/ExprEvaluator.kt
- komapper-template/src/test/kotlin/org/komapper/template/TwoWayTemplateStatementBuilderTest.kt
- komapper-template/src/test/kotlin/org/komapper/template/expression/ExprEvaluatorTest.kt
```kotlin
db.runQuery {
val sql = "select * from address where street = /*street*/'test'"
QueryDsl.fromTemplate(sql)
.bind("unknown", "STREET 10")
.select(asAddress)
}
```
The above code throws an exception with a stack trace like this:
```
org.komapper.template.sql.SqlException: The expression evaluation was failed at <select * from address where street = /*street*/'test'>:1:47.
...
Caused by: org.komapper.template.expression.ExprException: The variable "street" is not found. Make sure the variable name is correct. <street>:6
```
> Throws an understandable exception when a bind variable is not found in Template Queries

- integration-test-core/build.gradle.kts
- integration-test-jdbc/build.gradle.kts
- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcEntityMetamodels.kt
- integration-test-r2dbc/src/test/kotlin/integration/r2dbc/R2dbcEntityMetamodels.kt
- komapper-core/src/main/kotlin/org/komapper/core/EntityMetamodels.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/Meta.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/metamodel/EntityMetamodelFactory.kt
- komapper-core/src/main/kotlin/org/komapper/core/spi/EntityMetamodelFactory.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/Config.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/EmptySymbolProcessor.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/EntityMetamodelFactoryProcessor.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/EntityMetamodelFactoryProcessorProvider.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/EntityMetamodelGenerator.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/EntityProcessor.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/Symbols.kt
- komapper-processor/src/main/resources/META-INF/services/com.google.devtools.ksp.processing.SymbolProcessorProvider
- komapper-quarkus-jdbc-deployment/src/main/java/org/komapper/quarkus/jdbc/deployment/KomapperProcessor.java
If the KSP option "komapper.enableEntityMetamodelListing" is enabled, entity metamodels can be retrieved as a list.
build.gradle.kts:
```kotlin
ksp {
arg("komapper.enableEntityMetamodelListing", "true")
}
```
Sample.kt:
```kotlin
// get metamodels
val metamodels: List<EntityMetamodel<*, *, *>> = EntityMetamodels.list(Meta)
val db = JdbcDatabase("jdbc:h2:mem:example;DB_CLOSE_DELAY=-1")
// create tables using metamodels 
db.runQuery {
QueryDsl.create(metamodels)
}
```
> Add the KSP option "komapper.enableEntityMetamodelListing"

- integration-test-core/build.gradle.kts
- integration-test-core/src/main/kotlin/integration/core/Entities.kt
- integration-test-jdbc/build.gradle.kts
- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcSelectJoinTest.kt
- komapper-annotation/src/main/kotlin/org/komapper/annotation/Annotations.kt
- komapper-annotation/src/main/kotlin/org/komapper/annotation/AssociationType.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/query/EntityStore.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/query/EntityStoreContext.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/AnnotationSupport.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/Config.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/Data.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/EntityAnalyzer.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/EntityDefFactory.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/EntityDefinitionSourceResolver.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/EntityFactory.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/EntityMetamodelGenerator.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/EntityModel.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/EntityProcessor.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/ProcessorUtility.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/Symbols.kt
- komapper-processor/src/test/kotlin/org/komapper/processor/EntityProcessorErrorTest.kt
- komapper-processor/src/test/kotlin/org/komapper/processor/EntityProcessorOkTest.kt
The KomapperAssociation annotation simplifies EntityStore operations.
Entity definitions:
```kotlin
@KomapperAssociation(AssociationType.ONE_TO_MANY, Employee::class, "employees")
data class Department(
@KomapperId
@KomapperColumn("department_id")
val departmentId: Int,
@KomapperColumn("department_name")
val departmentName: String,
)
@KomapperEntity(["employee", "manager"])
@KomapperAssociation(AssociationType.MANY_TO_ONE, Department::class)
@KomapperAssociation(AssociationType.ONE_TO_ONE, Address::class)
data class Employee(
@KomapperId
@KomapperColumn("employee_id")
val employeeId: Int,
@KomapperColumn("employee_name")
val employeeName: String,
@KomapperColumn("department_id")
val departmentId: Int,
@KomapperColumn("address_id")
val addressId: Int,
)
data …
```
> Add the experimental association API

- integration-test-core/src/main/kotlin/integration/core/PostgreSqlSetting.kt
- integration-test-jdbc/src/postgresql/kotlin/integration/jdbc/postgresql/PostgreSqlEntities.kt
- integration-test-jdbc/src/postgresql/kotlin/integration/jdbc/postgresql/PostgreSqlInsertSingleTest.kt
- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcInsertSingleTest.kt
- komapper-core/src/main/kotlin/org/komapper/core/Dialect.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/builder/BuilderUtility.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/context/EntityInsertContext.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/context/EntityUpsertContext.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/options/InsertOptions.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/query/InsertOnDuplicateKeyUpdateQueryBuilder.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/query/InsertQueryBuilder.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/runner/EntityUpsertBatchRunner.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/runner/EntityUpsertMultipleRunner.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/runner/EntityUpsertSingleRunner.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/runner/RunnerUtility.kt
- komapper-dialect-h2/src/main/kotlin/org/komapper/dialect/h2/H2Dialect.kt
- komapper-dialect-h2/src/main/kotlin/org/komapper/dialect/h2/H2EntityUpsertStatementBuilder.kt
- komapper-dialect-mariadb/src/main/kotlin/org/komapper/dialect/mariadb/MariaDbDialect.kt
- komapper-dialect-mysql/src/main/kotlin/org/komapper/dialect/mysql/MySqlDialect.kt
- komapper-dialect-oracle/src/main/kotlin/org/komapper/dialect/oracle/OracleDialect.kt
- komapper-dialect-oracle/src/main/kotlin/org/komapper/dialect/oracle/OracleEntityUpsertStatementBuilder.kt
- komapper-dialect-postgresql/src/main/kotlin/org/komapper/dialect/postgresql/PostgreSqlDialect.kt
- komapper-dialect-postgresql/src/main/kotlin/org/komapper/dialect/postgresql/PostgreSqlEntityUpsertStatementBuilder.kt
- komapper-dialect-sqlserver/src/main/kotlin/org/komapper/dialect/sqlserver/SqlServerDialect.kt
- komapper-dialect-sqlserver/src/main/kotlin/org/komapper/dialect/sqlserver/SqlServerEntityUpsertStatementBuilder.kt
This pull request will enhance the functionality of `onDuplicateKeyUpdate` and `onDuplicateKeyIgnore`.
For example, the following code works for PostgreSQL:
```sql
create table if not exists friend(uuid1 uuid, uuid2 uuid, pending boolean, constraint pk_friend primary key(uuid1, uuid2));
create unique index friend_unique_idx on friend (greatest(uuid1, uuid2), least(uuid1, uuid2));
```
```kotlin
data class Friend(
@KomapperId
val uuid1: UUID,
@KomapperId
val uuid2: UUID,
val pending: Boolean,
)
```
```kotlin
@Test
fun dangerouslyOnDuplicateKeyUpdate() {
val f = Meta.friend
val friend = Friend(UUID.randomUUID(), UUID.randomUUID(), false)
db.runQuery(QueryDsl.insert(f).single(friend))
db.runQuery(
QueryDsl.insert(f)
.dangerouslyOnDuplicateKeyUpdate("(greatest(uuid1, uuid2), …
```
> Support specifying serach conditions and a conflict target in upsert statements

- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcSessionTest.kt
- integration-test-r2dbc/src/test/kotlin/integration/r2dbc/R2dbcSessionTest.kt
- komapper-jdbc/src/main/kotlin/org/komapper/jdbc/JdbcSession.kt
- komapper-quarkus-jdbc/src/main/kotlin/org/komapper/quarkus/jdbc/QuarkusJdbcTransactionSession.kt
- komapper-r2dbc/src/main/kotlin/org/komapper/r2dbc/R2dbcSession.kt
- komapper-spring-jdbc/src/main/kotlin/org/komapper/spring/jdbc/SpringJdbcTransactionSession.kt
- komapper-spring-r2dbc/src/main/kotlin/org/komapper/spring/r2dbc/SpringR2dbcTransactionSession.kt
- komapper-tx-context-jdbc/src/main/kotlin/org/komapper/tx/context/jdbc/ContextualJdbcDatabase.kt
- komapper-tx-context-r2dbc/src/main/kotlin/org/komapper/tx/context/r2dbc/ContextualR2dbcDatabase.kt
- komapper-tx-jdbc/src/main/kotlin/org/komapper/tx/jdbc/JdbcTransactionSession.kt
- komapper-tx-r2dbc/src/main/kotlin/org/komapper/tx/r2dbc/R2dbcTransactionSession.kt
This pull request makes available the DataSource and ConnectionFactory managed by Komapper.
JDBC:
```kotlin
val db: JdbcDatabase = ...
val dataSource: DataSource = db.config.session.dataSource
```
R2DBC:
```kotlin
val db: R2dbcDatabase = ...
val connectionFactory: ConnectionFactory = db.config.session.connectionFactory
```
> Expose DataSource and ConnectionFactory

- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcOperatorTest.kt
- komapper-core/src/main/kotlin/org/komapper/core/Dialect.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/builder/BuilderSupport.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/expression/MathematicalFunction.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/operator/MathematicalFunctions.kt
- komapper-dialect-mariadb/src/main/kotlin/org/komapper/dialect/mariadb/MariaDbDialect.kt
- komapper-dialect-mysql/src/main/kotlin/org/komapper/dialect/mysql/MySqlDialect.kt
- komapper-dialect-oracle/src/main/kotlin/org/komapper/dialect/oracle/OracleDialect.kt
- komapper-dialect-sqlserver/src/main/kotlin/org/komapper/dialect/sqlserver/SqlServerDialect.kt
The `random()` function is defined in the `org.komapper.core.dsl.operator` package.
We can use it as follows:
```kotlin
val result = db.runQuery {
QueryDsl.from(a).orderBy(random())
}
```
Running the above query will issue the following SQL:
```sql
select t0_.address_id, t0_.street, t0_.version from address as t0_ order by random() asc
```
> Support for the random function

- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcInsertMultipleReturningTest.kt
- integration-test-r2dbc/src/test/kotlin/integration/r2dbc/R2dbcInsertMultipleReturningTest.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/query/InsertQueryBuilder.kt
This code should work:
```kotlin
val addressList = db.runQuery {
QueryDsl.insert(a)
.multiple(
Address(16, "STREET 16", 0),
Address(17, "STREET 17", 0),
Address(18, "STREET 18", 0),
)
.returning()
}
```
> Fix incorrect return type of InsertQueryBuilder#multiple

- build.gradle.kts
- settings.gradle.kts
See https://spring.io/blog/2022/12/14/notice-of-permissions-changes-to-repo-spring-io-january-2023
> Download Spring releases from Maven Central.

- komapper-codegen/src/test/kotlin/org/komapper/codegen/CodeGeneratorTest.kt
`.trimIndent()` always changes the line separator to `LF`. Therefore, the code generation test fails on Windows.
I have fixed the test because fixing the line separator of code generation to `LF` affects users.
> Fix CodeGeneratorTest failure on Windows

- gradle-plugin/src/main/java/org/komapper/gradle/codegen/GenerateTask.java
- gradle-plugin/src/main/java/org/komapper/gradle/codegen/Generator.java
- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcMetadataReaderTest.kt
- komapper-codegen/src/main/java/org/komapper/codegen/CodeGenerator.java
- komapper-codegen/src/test/kotlin/org/komapper/codegen/CodeGeneratorTest.kt
Hello.
Well, I would like to automatically generate `@KomapperVersion`, `@KomapperCreatedAt` and `@KomapperUpdatedAt` annotations, and I have implemented this.
Please merge this if you like.
> Support `@KomapperVersion`, `@KomapperCreatedAt` and `@KomapperUpdatedAt` in code generator

- komapper-tx-r2dbc/src/main/kotlin/org/komapper/tx/r2dbc/R2dbcTransactionManager.kt
- komapper-tx-r2dbc/src/test/kotlin/org/komapper/tx/r2dbc/MultipleDatabasesTest.kt
- komapper-tx-r2dbc/src/test/kotlin/org/komapper/tx/r2dbc/Person.kt
To identify transactions, each transaction manager uses its own CoroutineContext.Key.
> Separate R2DBC transactions per session

- gradle-plugin/src/main/java/org/komapper/gradle/codegen/GenerateTask.java
- gradle-plugin/src/main/java/org/komapper/gradle/codegen/Generator.java
- komapper-codegen/src/main/java/org/komapper/codegen/CodeGenerator.java
- komapper-codegen/src/test/kotlin/org/komapper/codegen/CodeGeneratorTest.kt
Singularizing entity class names and having access to the metamodel with the same name as the table name were originally separate concerns and should have been accomplished with separate options.
The `singularize` option concentrates only on converting to singular entity class names, and the `useTableNameAsAlias` option was added to generate an alias that is the same as the table name.
Close #1015
> Add the `useTableNameAsAlias` option to Gradle plugin

- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcDeleteBatchTest.kt
- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcUpdateBatchTest.kt
- komapper-dialect-mariadb/src/main/kotlin/org/komapper/dialect/mariadb/MariaDbDialect.kt
See also https://mariadb.com/kb/en/mariadb-connector-j-3-2-0-release-notes/#batch-bulk-behavior
> Support optimistic locking of batch execution in MariaDB

- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcDeleteWhereReturningTest.kt
- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcDeleteWhereTest.kt
- integration-test-r2dbc/src/test/kotlin/integration/r2dbc/R2dbcDeleteWhereReturningTest.kt
- integration-test-r2dbc/src/test/kotlin/integration/r2dbc/R2dbcDeleteWhereTest.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/query/DeleteQueryBuilder.kt
You can write as follows:
```kotlin
QueryDsl.delete(e).all()
```
instead of:
```kotlin
QueryDsl.delete(e).all().options { it.copy(allowMissingWhereClause = true) }
```
> Enable the `allowMissingWhereClause` option in DELETE ALL queries

- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcOperatorTest.kt
- komapper-core/src/main/kotlin/org/komapper/core/Dialect.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/builder/BuilderSupport.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/expression/StringFunction.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/operator/StringFunctions.kt
- komapper-dialect-oracle/src/main/kotlin/org/komapper/dialect/oracle/OracleDialect.kt
- komapper-dialect-postgresql/src/main/kotlin/org/komapper/dialect/postgresql/PostgreSqlDialect.kt
- komapper-dialect-sqlserver/src/main/kotlin/org/komapper/dialect/sqlserver/SqlServerDialect.kt
This PR supports the locate function.
Komapper query:
```kotlin
val result = db.runQuery {
QueryDsl.from(a).select(locate("bar", literal("foobarbar"), 5)).first()
}
assertEquals(7, result)
```
The above query is converted to the following SQL depending on Dialect:
```sql
-- H2, MySQL, MariaDB
select (locate('bar', 'foobarbar', 5)) from address as t0_
-- Oracle
select (instr('foobarbar', 'bar', 5)) from address as t0_
-- PostgreSQL
select (position('bar' in substring('foobarbar' from 5)) + 5 - 1) from address as t0_
-- SQL Server
select (charindex('bar', 'foobarbar', 5)) from address as t0_
```
- https://www.h2database.com/html/functions.html#locate
- https://mariadb.com/kb/en/locate/
- https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_locate
- …
> Support the locate function

- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcOperatorTest.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/builder/BuilderSupport.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/expression/ColumnExpression.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/expression/LiteralExpression.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/expression/UserDefinedExpression.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/operator/OperatorUtility.kt
- komapper-core/src/test/kotlin/org/komapper/core/dsl/operator/LiteralExpressionsTest.kt
- komapper-core/src/test/kotlin/org/komapper/core/dsl/operator/OperatorUtilityTest.kt
For example, Komapper does not provide a regexp operator, but users can define and use it in their queries.
Define the regexp expression:
```kotlin
fun regexp(
left: ColumnExpression<String, String>,
right: String,
): ColumnExpression<Int, Int> {
val o1 = Operand.Column(left)
val o2 = Operand.Argument(left, right)
return columnExpression(Int::class, listOf(o1, o2)) {
visit(o1)
append(" regexp ")
visit(o2)
}
}
```
Use it in your query:
```kotlin
QueryDsl.from(a).select(regexp(literal("hello"), ".*")).first()
```
The above query is converted to the following SQL:
```sql
select ('hello' regexp '.*') from address as t0_
```
> Support adding user-defined column expressions

- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcSelectWhereTest.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/builder/BuilderSupport.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/expression/Criterion.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/operator/CriteriaContext.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/scope/FilterScope.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/scope/FilterScopeSupport.kt
For example, Komapper does not provide a `~` and `!~` operators, but users can define and use them in their queries.
Define the operators:
```kotlin
class MyExtension(private val context: CriteriaContext) {
infix fun <T : Any> ColumnExpression<T, String>.`~`(pattern: T?) {
if (pattern == null) return
val o1 = Operand.Column(this)
val o2 = Operand.Argument(this, pattern)
context.add {
visit(o1)
append(" ~ ")
visit(o2)
}
}
infix fun <T : Any> ColumnExpression<T, String>.`!~`(pattern: T?) {
if (pattern == null) return
val o1 = Operand.Column(this)
val o2 = Operand.Argument(this, pattern)
context.add {
visit(o1)
append(" !~ ")
visit(o2)
}
}
}
```
Use them in your query:
```kotlin
QueryDsl.from(e).where {
e.salary greaterEq BigDecimal(1000)
extension(::MyExtension) { …
```
> Support adding user-defined comparison operators

- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcSelectWhereTest.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/builder/BuilderUtility.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/expression/ConditionalExpression.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/operator/CriteriaContext.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/operator/EscapeExpressions.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/scope/FilterScope.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/scope/FilterScopeSupport.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/scope/HavingScope.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/scope/OnScope.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/scope/WhenScope.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/scope/WhereScope.kt
With this fix, the following query will work correctly.
```kotlin
QueryDsl.from(e).where {
e.salary greaterEq BigDecimal(1000)
extension(::MyExtension) {
e.employeeName `~` "S"
or {
e.employeeName `~` "T"
}
}
}.orderBy(e.employeeName)
```
```kotlin
class MyExtension(private val context: CriteriaContext) {
infix fun <T : Any> ColumnExpression<T, String>.`~`(pattern: T?) {
if (pattern == null) return
val o1 = Operand.Column(this)
val o2 = Operand.Argument(this, pattern)
context.add {
visit(o1)
append(" ~ ")
visit(o2)
}
}
infix fun <T : Any> ColumnExpression<T, String>.`!~`(pattern: T?) {
if (pattern == null) return
val o1 = Operand.Column(this)
val o2 = Operand.Argument(this, pattern)
context.add {
visit(o1)
append(" !~ ")
visit(o2)
}
}
}
```
> Fix the bug that generates invalid SQL when performing logical operations in extension blocks

- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcInsertSingleTest.kt
- integration-test-r2dbc/src/test/kotlin/integration/r2dbc/R2dbcInsertSingleTest.kt
- komapper-dialect-mariadb/src/main/kotlin/org/komapper/dialect/mariadb/MariaDbDialect.kt
- komapper-dialect-mariadb/src/main/kotlin/org/komapper/dialect/mariadb/MariaDbEntityUpsertStatementBuilder.kt
We will support the execution of queries like the following in MariaDB:
```kotlin
val d = Meta.department
val department = Department(1, 50, "PLANNING", "TOKYO", 10)
val query = QueryDsl.insert(d).onDuplicateKeyUpdate().set { excluded ->
d.departmentName eq "PLANNING2"
d.location eq concat(d.location, concat("_", excluded.location))
}.single(department)
```
The above query will be converted to the following SQL:
```sql
insert into department 
(department_id, department_no, department_name, location, version) 
values 
(1, 50, 'PLANNING', 'TOKYO', 10)
on duplicate key update 
department_name = 'PLANNING2', 
location = (concat(department.location, (concat('_', values(location)))))
```
> Emulate the excluded column using the VALUES clause in MariaDB

- integration-test-core/src/main/kotlin/integration/core/PostgreSqlSetting.kt
- integration-test-jdbc/gradle.properties
- integration-test-jdbc/src/postgresql/kotlin/integration/jdbc/postgresql/JdbcPostgreSqlSetting.kt
- integration-test-r2dbc/gradle.properties
- integration-test-r2dbc/src/postgresql/kotlin/integration/r2dbc/postgresql/PostgreSqlEntities.kt
- integration-test-r2dbc/src/postgresql/kotlin/integration/r2dbc/postgresql/R2dbcPostgreSqlMapping.kt
- integration-test-r2dbc/src/postgresql/kotlin/integration/r2dbc/postgresql/R2dbcPostgreSqlMappingTest.kt
- integration-test-r2dbc/src/postgresql/kotlin/integration/r2dbc/postgresql/R2dbcPostgreSqlSetting.kt
- integration-test-r2dbc/src/postgresql/kotlin/integration/r2dbc/postgresql/R2dbcPostgreSqlTypeTest.kt
- komapper-dialect-postgresql-r2dbc/build.gradle.kts
- komapper-dialect-postgresql-r2dbc/src/main/kotlin/org/komapper/dialect/postgresql/r2dbc/PostgreSqlR2dbcBoxType.kt
- komapper-dialect-postgresql-r2dbc/src/main/kotlin/org/komapper/dialect/postgresql/r2dbc/PostgreSqlR2dbcCircleType.kt
- komapper-dialect-postgresql-r2dbc/src/main/kotlin/org/komapper/dialect/postgresql/r2dbc/PostgreSqlR2dbcDataTypeProvider.kt
- komapper-dialect-postgresql-r2dbc/src/main/kotlin/org/komapper/dialect/postgresql/r2dbc/PostgreSqlR2dbcGeometryType.kt
- komapper-dialect-postgresql-r2dbc/src/main/kotlin/org/komapper/dialect/postgresql/r2dbc/PostgreSqlR2dbcLineType.kt
- komapper-dialect-postgresql-r2dbc/src/main/kotlin/org/komapper/dialect/postgresql/r2dbc/PostgreSqlR2dbcLsegType.kt
- komapper-dialect-postgresql-r2dbc/src/main/kotlin/org/komapper/dialect/postgresql/r2dbc/PostgreSqlR2dbcPathType.kt
- komapper-dialect-postgresql-r2dbc/src/main/kotlin/org/komapper/dialect/postgresql/r2dbc/PostgreSqlR2dbcPointType.kt
- komapper-dialect-postgresql-r2dbc/src/main/kotlin/org/komapper/dialect/postgresql/r2dbc/PostgreSqlR2dbcPolygonType.kt
We have supported the following geometric data types.
- box
- circle
- line
- lseg
- geometry
- path
- point
- polygon
> Support geometric types in the Dialect for PostgreSQL R2DBC

- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcSelectSubqueryTest.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/QueryDsl.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/builder/BuilderSupport.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/context/SubqueryContext.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/expression/AliasExpression.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/expression/SubqueryExpression.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/metamodel/InlineViewMetamodel.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/query/Record.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/query/RelationSelectQuery.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/query/RelationSetOperationQuery.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/query/SelectQuery.kt
We have added support for Inline Views.
For example, you can write as follows:
```kotlin
val d = Meta.department
val inlineView = QueryDsl.from(e)
.innerJoin(d) { e.departmentId eq d.departmentId }
.groupBy(d.departmentName)
.select(d.departmentName, sum(e.salary))
val query = QueryDsl.from(inlineView).orderBy(inlineView[d.departmentName])
```
The above query will be converted into the following SQL:
```sql
select 
t0_."c0_department_name_", 
t0_."c1_salary_" 
from (
select 
t2_.department_name as "c0_department_name_", 
sum(t1_.salary) as "c1_salary_" 
from 
employee as t1_ 
inner join 
department as t2_ on (t1_.department_id = t2_.department_id) 
group by 
t2_.department_name
) as t0_ 
order by 
t0_."c0_department_name_" asc
```
> Support inline views

- integration-test-core/src/main/kotlin/integration/core/Entities.kt
- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcSelectProjectionTest.kt
- komapper-annotation/src/main/kotlin/org/komapper/annotation/Annotations.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/AnnotationSupport.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/Config.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/Data.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/EntityDefFactory.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/EntityFactory.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/EntityMetamodelGenerator.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/Symbols.kt
This PR introduces the followings:
- The `@KomapperProjection` annotation
- The `komapper.enableEntityProjection` option for annotation processor
We can define an entity class with the `@KomapperProjection` annotation as follows:
```kotlin
@KomapperProjection
data class Address(
@KomapperId
@KomapperColumn(name = "address_id")
val addressId: Int,
val street: String,
@KomapperVersion val version: Int,
)
```
The above definition generates the `selectAsAddress` extension function.
The `selectAsAddress` function can be used as follows:
```kotlin
val query: Query<List<Address>> = QueryDsl.from(e)
.where { e.employeeName startsWith "S" }
.selectAsAddress(
version = e.version,
addressId = e.employeeId,
street = concat(e.employeeName, " STREET"),
)
```
When …
> Enables the projection of SELECT query into an entity

- .github/workflows/labeler.yml
This reverts commit 0f5ab25ddb9ebf10d739a6a04c221758bd595a33.
It seems that there is an issue with labeler action v5.
https://github.com/actions/labeler/issues/712
> Revert "Update actions/labeler action to v5 (#1153)"

- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcSelectTest.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/builder/BuilderSupport.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/expression/Operand.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/operator/OperatorUtility.kt
**BEFORE**
```kotlin
private fun fromUnixTime(value: Long): ColumnExpression<LocalDateTime, LocalDateTime> {
val name = "fromUnixTime"
val o1 = Operand.Argument(literal(0L), value)
return columnExpression(LocalDateTime::class, LocalDateTime::class, { it }, name, listOf(o1)) {
append("FROM_UNIXTIME(")
visit(o1)
append(")")
}
}
```
**AFTER**
```kotlin
private fun fromUnixTime(value: Long): ColumnExpression<LocalDateTime, LocalDateTime> {
val name = "fromUnixTime"
val o1 = Operand.SimpleArgument(Long::class, value)
return columnExpression(LocalDateTime::class, name, listOf(o1)) {
append("FROM_UNIXTIME(")
visit(o1)
append(")")
}
}
```
> Simplify the creation of custom column expressions

- integration-test-core/src/main/kotlin/integration/core/Entities.kt
- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcUpdateBatchTest.kt
- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcUpdateSingleTest.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/builder/EntityUpdateStatementBuilder.kt
I am currently getting the following error when empty update columns.
but, that error was hard to understand cause. so added validation.
In Doma, no error occurs as it is not updated, but in Komapper nothing feature the sqlExecutionSkip(AutoBatchModifyQuery#isExecutable and AutoBatchModifyQuery#getSqlExecutionSkipCause in Doma). so I added validation by require-method.
```
org.komapper.jdbc.JdbcException: org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "update address se [*]where address_id = ? and street = ? and version = ?"; expected "SET"; SQL statement:
update address se where address_id = ? and street = ? and version = ? [42001-224]
at org.komapper.jdbc.DefaultJdbcExecutor.withExceptionTranslator(JdbcExecutor.kt:184)
at …
```
> Added validation to ensure that the update columns are not empty in AutoBatchUpdateQuery

- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcSelectWithTest.kt
- komapper-core/src/main/kotlin/org/komapper/core/Dialect.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/builder/SelectStatementBuilder.kt
In at least one case, namely ClickHouse, the following syntax is not supported:
```sql
with my_table (a, b, c) as (select ...) ...
```
but is instead limited to
```sql
with my_table as (select ...) ...
```
So I'm adding a configuration option to make expansion of column names optional within a dialect.
This follows this [discussion](https://kotlinlang.slack.com/archives/C03JF82SDHA/p1704895714562399?thread_ts=1704884009.087219&cid=C03JF82SDHA) that happened in Kotlin Slack.
> Add dialect configuration to control whether output column names are included in a CTE definition.

- integration-test-core/src/main/kotlin/integration/core/Entities.kt
- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcSelectProjectionTest.kt
- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcTemplateTest.kt
- komapper-annotation/src/main/kotlin/org/komapper/annotation/Annotations.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/ProjectionMeta.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/builder/BuilderSupport.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/context/SetOperationContext.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/expression/LiteralExpression.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/expression/ReadOnlyColumnExpression.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/operator/LiteralExpressions.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/operator/OperatorUtility.kt
- komapper-jdbc/src/main/kotlin/org/komapper/jdbc/dsl/runner/JdbcEntityMapper.kt
- komapper-jdbc/src/main/kotlin/org/komapper/jdbc/dsl/runner/JdbcResultSetTransformers.kt
- komapper-jdbc/src/main/kotlin/org/komapper/jdbc/dsl/visitor/JdbcQueryVisitor.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/AnnotationSupport.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/Data.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/EntityAnalyzer.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/EntityDefFactory.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/EntityDefinitionSourceResolver.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/EntityFactory.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/EntityMetamodelGenerator.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/EntityProcessor.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/EntityProcessorProvider.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/ProcessingAnnotation.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/Symbols.kt
- komapper-r2dbc/src/main/kotlin/org/komapper/r2dbc/dsl/runner/R2dbcEntityMapper.kt
- komapper-r2dbc/src/main/kotlin/org/komapper/r2dbc/dsl/runner/R2dbcRowTransformers.kt
- komapper-r2dbc/src/main/kotlin/org/komapper/r2dbc/dsl/visitor/R2dbcFlowQueryVisitor.kt
- komapper-r2dbc/src/main/kotlin/org/komapper/r2dbc/dsl/visitor/R2dbcQueryVisitor.kt
The class annotated with `@KomapperProjection` no longer needs to have `@KomapperId`.
**Entity and Projection**
```kotlin
data class Person(@KomapperId val id:Int, val firstName: String, val lastName: String, val age: Int)
@KomapperProjection
data class PersonDto(val name: String, val age: Int)
```
**Query**
```kotlin
val p = Meta.person
val query: Query<List<PersonDto>> = QueryDsl.from(p)
.selectAsPersonDto(
name = concat(concat(p.fristName, " "), p.lastName), 
age = p.age,
)
```
> Make `@KomapperProjection` independent from `@KomapperEntity`

- komapper-spring-r2dbc/src/main/kotlin/org/komapper/spring/r2dbc/SpringR2dbcTransactionSession.kt
- komapper-spring-r2dbc/src/test/kotlin/org/komapper/spring/r2dbc/SpringR2dbcTransactionSessionTest.kt
In Spring Framework version 6, it seems that the autoCommit flag for R2DBC's Connection is no longer used for transaction management. Therefore, the presence of a transaction is now determined using the TransactionContextManager.
> In both Spring Framework version 5 and version 6, if there is no transaction, close the connection

- komapper-r2dbc/src/main/kotlin/org/komapper/r2dbc/R2dbcSession.kt
- komapper-tx-context-r2dbc/src/main/kotlin/org/komapper/tx/context/r2dbc/ContextualR2dbcDatabase.kt
- komapper-tx-r2dbc/src/main/kotlin/org/komapper/tx/r2dbc/R2dbcTransactionConnection.kt
- komapper-tx-r2dbc/src/main/kotlin/org/komapper/tx/r2dbc/R2dbcTransactionSession.kt
This method should correctly convey the context.
> The closing of R2DBC connections is performed by first converting it into a Flow

- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcInsertSingleTest.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/context/EntityInsertContext.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/context/EntityUpsertContext.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/query/InsertOnDuplicateKeyUpdateQueryBuilder.kt
- komapper-dialect-h2/src/main/kotlin/org/komapper/dialect/h2/H2EntityUpsertStatementBuilder.kt
- komapper-dialect-oracle/src/main/kotlin/org/komapper/dialect/oracle/OracleEntityUpsertStatementBuilder.kt
- komapper-dialect-postgresql/src/main/kotlin/org/komapper/dialect/postgresql/PostgreSqlEntityUpsertStatementBuilder.kt
- komapper-dialect-sqlserver/src/main/kotlin/org/komapper/dialect/sqlserver/SqlServerEntityUpsertStatementBuilder.kt
```kotlin
val query = QueryDsl.insert(a).onDuplicateKeyIgnore().single(address)
```
The above query corresponds to the following SQL.
Please note that no columns are specified after "on conflict".
```sql
insert into address as t0_ (address_id, street, version) values (?, ?, ?) on conflict do nothing
```
To specify particular columns, the following query is needed.
```kotlin
val query = QueryDsl.insert(a).onDuplicateKeyIgnore(a.street).single(address)
```
The above query corresponds to the following SQL.
```sql
insert into address as t0_ (address_id, street, version) values (?, ?, ?) on conflict (street) do nothing
```
> Change to not specify conflict_target by default for ON CONFLICT DO NOTHING in PostgreSQL

- komapper-core/src/main/kotlin/org/komapper/core/dsl/query/EntityStore.kt
We have added a note to the EntityStore source code and [the Association API documentation](https://www.komapper.org/docs/reference/association/).
Close #1256
> Specify that Maps and Sets preserve the order of elements

- komapper-processor/src/main/kotlin/org/komapper/processor/Context.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/KomapperKSPLogger.kt
The output example is as follows:
> [ksp] The entity class must have at least one id property. file:///Users/nakamura/src/github.com/komapper/komapper-quickstart/src/main/kotlin/org/komapper/quickstart/Employee.kt:7
> Add location information to the output of KSPLogger

- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcOperatorTest.kt
- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcSelectTest.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/expression/Operand.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/expression/UserDefinedExpression.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/operator/OperatorUtility.kt
To simplify the definition, use type parameters instead of KType parameters.
This change is related to #1303.
> Simplify the definition of custom column expressions

- integration-test-core/build.gradle.kts
- integration-test-core/src/main/kotlin/integration/core/Dbms.kt
- integration-test-core/src/main/kotlin/integration/core/Entities.kt
- integration-test-core/src/main/kotlin/integration/core/EntitiesDataType.kt
- integration-test-core/src/main/kotlin/integration/core/EntitiesKeyword.kt
- integration-test-core/src/main/kotlin/integration/core/EntitiesKotlinDatetime.kt
- integration-test-core/src/main/kotlin/integration/core/EntitiesQuote.kt
- integration-test-core/src/main/kotlin/integration/core/EntitiesSchema.kt
- integration-test-core/src/main/kotlin/integration/core/EntitiesUnit.kt
- integration-test-core/src/main/kotlin/integration/core/EntitiesValueClass.kt
- integration-test-core/src/main/kotlin/integration/core/EntitiesVirtual.kt
- integration-test-core/src/main/kotlin/integration/core/H2Setting.kt
- integration-test-core/src/main/kotlin/integration/core/LogConfigurator.kt
- integration-test-core/src/main/kotlin/integration/core/MariaDbSetting.kt
- integration-test-core/src/main/kotlin/integration/core/MySql5Setting.kt
- integration-test-core/src/main/kotlin/integration/core/MySqlSetting.kt
- integration-test-core/src/main/kotlin/integration/core/OracleSetting.kt
- integration-test-core/src/main/kotlin/integration/core/PostgreSqlSetting.kt
- integration-test-core/src/main/kotlin/integration/core/Run.kt
- integration-test-core/src/main/kotlin/integration/core/Setting.kt
- integration-test-core/src/main/kotlin/integration/core/SqlServerSetting.kt
- integration-test-core/src/main/kotlin/integration/core/WrappedStringTypeConverter.kt
- integration-test-core/src/main/kotlin/integration/core/enumclass/Color.kt
- integration-test-core/src/main/kotlin/integration/core/enumclass/Direction.kt
- integration-test-core/src/main/kotlin/integration/core/enumclass/Mood.kt
- integration-test-core/src/main/kotlin/integration/core/one/MyTestModel.kt
- integration-test-core/src/main/kotlin/integration/core/two/AnotherModel.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/BackquotedSymbols.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/EntityMetamodelGenerator.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/EntityMetamodelStubGenerator.kt
We have decided to make visibility and return types explicit in the code generated by KSP.
The integration-test-core module is used to test whether the code is generated correctly.
> Support explicit API in the code generated by KSP

- integration-test-core/build.gradle.kts
- integration-test-jdbc/build.gradle.kts
- komapper-tx-context-jdbc/build.gradle.kts
- komapper-tx-context-r2dbc/build.gradle.kts
Based on the Gradle warning messages, we will set the compilation options using the suggested approach.
> Use the compilerOptions property

- integration-test-core/src/test/kotlin/integration/core/QueryDslTest.kt
- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcSelectTest.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/QueryDsl.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/context/EntityDeleteContext.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/context/EntityInsertContext.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/context/EntityUpdateContext.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/context/RelationDeleteContext.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/context/RelationUpdateContext.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/context/SchemaContext.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/context/ScriptContext.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/context/SelectContext.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/context/SetOperationContext.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/context/SubqueryContext.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/options/DeleteOptions.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/options/InsertOptions.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/options/SchemaOptions.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/options/ScriptOptions.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/options/SelectOptions.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/options/TemplateExecuteOptions.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/options/TemplateSelectOptions.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/options/UpdateOptions.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/query/FlowSubquerySupport.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/query/SelectQueryBuilder.kt
Previously, it was necessary to set query options for each query.
```kotlin
val query1 = QueryDsl.from(a)
.options {
it.copy(
queryTimeoutSeconds = 10,
)
}
val list1 = db.runQuery(query1)
val query2 = QueryDsl.from(a)
.where { a.addressId greater 10 }
.options {
it.copy(
queryTimeoutSeconds = 10,
)
}
val list2 = db.runQuery(query2)
```
From now on, you will only need to configure the query options once for each instantiated QueryDsl. The query options will be shared across the same instance.
```kotlin
val myDsl = QueryDsl(selectOptions = SelectOptions(queryTimeoutSeconds = 10))    
val query1 = myDsl.from(a)
val list1 = db.runQuery(query1)
val query2 = myDsl.from(a).where { a.addressId greater 10 }
val list2 = db.runQuery(query2)
```
Of course, …
> Make QueryDsl instantiable and carry over query options settings

- komapper-processor/src/main/kotlin/org/komapper/processor/EntityMetamodelFactoryProcessor.kt
This PR avoids KtInvalidLifetimeOwnerAccessException in KSP 2.0.0-1.0.24.
For more details: https://github.com/google/ksp/issues/1854
> Prevent elements from being used across rounds

- integration-test-core/src/test/kotlin/integration/core/EntityMetamodelTest.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/expression/ColumnExpression.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/expression/PropertyExpression.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/expression/TableExpression.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/metamodel/EntityMetamodel.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/metamodel/EntityMetamodelDeclaration.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/metamodel/EntityMetamodelScope.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/metamodel/PropertyMetamodel.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/BackquotedSymbols.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/EntityMetamodelGenerator.kt
This PR allows retrieving `PropertyMetamodel` by name from `EntityMetamodel`. For example, you can do the following:
```kotlin
val date: PropertyMetamodel<Address, *, *>? = Meta.address["date"]
```
Practically, this can be useful when dynamically constructing common search conditions across multiple tables.
```kotlin
fun main() {
val query1 = QueryDsl.from(a).where {
addCommonWhere(a)
a.street eq "Tokyo"
}
val query2 = QueryDsl.from(e).where {
addCommonWhere(e)
e.departmentId eq 1
}
}
private fun <ENTITY: Any, ID: Any, META: EntityMetamodel<ENTITY, ID, META>> WhereScope.addCommonWhere(meta: META) {
val date = meta["date"] as PropertyMetamodel<ENTITY, LocalDate, LocalDate>
val where: WhereDeclaration =  {
date greater LocalDate.now()
} …
```
> Add get operator to EntityMetamodel

- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcSelectTest.kt
- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcSelectWhereTest.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/QueryDsl.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/scope/FilterScope.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/scope/FilterScopeSupport.kt
We've updated the between and notBetween operators to accept Pair types for ColumnExpression.
```kotlin
val start = QueryDsl.select(max(literal(5)))
val end = QueryDsl.select(max(literal(10)))
val query = QueryDsl.from(a).where {
a.addressId between (start to end)
}.orderBy(a.addressId)
```
> Support subquery for between and notBetween operators

- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcTemplateTest.kt
- integration-test-r2dbc/src/test/kotlin/integration/r2dbc/R2dbcTemplateTest.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/context/TemplateExecuteContext.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/context/TemplateSelectContext.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/query/TemplateExecuteQuery.kt
- komapper-jdbc/src/main/kotlin/org/komapper/jdbc/dsl/runner/JdbcTemplateEntityProjectionSelectRunner.kt
- komapper-jdbc/src/main/kotlin/org/komapper/jdbc/dsl/runner/JdbcTemplateSelectRunner.kt
We can write as follows:
```kotlin
val sql = """
insert into address
(address_id, street, version)
values
(/*id*/0, /*street*/'', /*version*/0)
returning address_id, street, version
""".trimIndent()
QueryDsl.executeTemplate(sql)
.returning()
.bind("id", 16)
.bind("street", "NY street")
.bind("version", 1)
.select(asAddress)
.single()
```
However, the SQL for returning result sets varies by DBMS. For example, the above example works in PostgreSQL, but not in MySQL. It is the user's responsibility to write SQL that is compatible with their specific DBMS.
> Support returning result sets when executing INSERT, UPDATE, and DELETE using SQL templates

- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcCommandTest.kt
- komapper-core/src/main/kotlin/org/komapper/core/template/expression/ExprNode.kt
- komapper-core/src/main/kotlin/org/komapper/core/template/expression/ExprParser.kt
- komapper-core/src/main/kotlin/org/komapper/core/template/expression/ExprReducer.kt
- komapper-core/src/main/kotlin/org/komapper/core/template/expression/ExprTokenType.kt
- komapper-core/src/main/kotlin/org/komapper/core/template/expression/ExprTokenizer.kt
- komapper-core/src/test/kotlin/org/komapper/core/template/expression/ExprParserTest.kt
- komapper-core/src/test/kotlin/org/komapper/core/template/expression/ExprTokenizerTest.kt
- komapper-core/src/test/kotlin/org/komapper/core/template/sql/SqlParserTest.kt
- komapper-core/src/test/kotlin/org/komapper/core/template/sql/SqlTokenizerTest.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/command/ExprValidator.kt
- komapper-template/src/main/kotlin/org/komapper/template/ExprEvaluator.kt
- komapper-template/src/test/kotlin/org/komapper/template/ExprEvaluatorTest.kt
For example, this PR supports code like the following:
```kotlin
@KomapperCommand(
"""
insert into address
(address_id, street, version)
values
(/* id() */0, /* hello("world") */'', /* add(1, 2) */0)
""",
)
class AddAddress(val id: () -> Int, val hello: (String) -> String, val add: (Int, Int) -> Int) : Exec()
```
> Enable binding functions to SQL templates

- komapper-core/src/main/kotlin/org/komapper/core/Statement.kt
Making the constructor public suppresses the following warning message:
> Non-public primary constructor is exposed via the generated 'copy()' method of the 'data' class.
> Make the constructor of `DryRunStatement` public

- .github/workflows/build.yml
- gradle.properties
- komapper-core/src/main/kotlin/org/komapper/core/template/expression/ExprException.kt
- komapper-core/src/main/kotlin/org/komapper/core/template/sql/SqlException.kt
- komapper-core/src/main/kotlin/org/komapper/core/template/sql/SqlReassembler.kt
- komapper-core/src/test/kotlin/org/komapper/core/template/sql/SqlReassemblerTest.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/Context.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/command/CommandAnalyzer.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/command/CommandFactory.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/command/CommandProcessorProvider.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/command/ExprValidator.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/command/SqlValidator.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/entity/EntityProcessor.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/entity/EntityProcessorProvider.kt
- komapper-processor/src/test/kotlin/org/komapper/processor/command/CommandProcessorErrorTest.kt
- komapper-processor/src/test/kotlin/org/komapper/processor/command/ExprValidatorTest.kt
- komapper-processor/src/test/kotlin/org/komapper/processor/command/SqlValidatorTest.kt
- Fixed an issue where comparison operations would fail.
- Fixed an issue where literal variable directives were not handled correctly when reassembling SQL.
- Prohibited the command class from being nested within a private class.
> Fix and improve `CommandProcessor` and related classes

- komapper-core/src/main/kotlin/org/komapper/core/template/expression/ExprException.kt
- komapper-core/src/main/kotlin/org/komapper/core/template/sql/SqlException.kt
This fix ensures that exceptions will trigger a rollback under transaction management in the Spring Framework.
> Inherit from RuntimeException instead of Exception

- integration-test-jdbc/gradle.properties
- integration-test-jdbc/src/test/resources/container-license-acceptance.txt
- integration-test-r2dbc/gradle.properties
- integration-test-r2dbc/src/test/resources/container-license-acceptance.txt
It seems that the Docker image of Microsoft SQL Server 2019-CU12-ubuntu-20.04 does not work on Ubuntu 22.04.5. Therefore, we have upgraded the version to 2019-CU28-ubuntu-20.04.
> Update SQL Server docker image to 2019-CU28-ubuntu-20.04

- komapper-processor/src/main/kotlin/org/komapper/processor/command/SqlValidator.kt
- komapper-processor/src/test/kotlin/org/komapper/processor/command/SqlValidatorTest.kt
- komapper-template/src/main/kotlin/org/komapper/template/TwoWayTemplateStatementBuilder.kt
- komapper-template/src/test/kotlin/org/komapper/template/TwoWayTemplateStatementBuilderTest.kt
This pull request adds the following utility variables to the `for` directive in SQL templates:
- *identifier*_next_comma - Returns `,` if the next iteration will be executed; otherwise, returns an empty string.
- *identifier*_next_and - Returns `and` if the next iteration will be executed; otherwise, returns an empty string.
- *identifier*_next_or - Returns `or` if the next iteration will be executed; otherwise, returns an empty string.
For example, if you wanted to output the OR operator in combination with the `for` directive, you previously had to write it as follows:
```sql
/*% for name in names */
employee_name like /* name */'hoge'
/*% if name_has_next */
/*# "or" */
/*% end */
/*% end */
```
However, by using one of the aforementioned utility variables, you can write it more …
> Add some utility variables to the `for` directive

- integration-test-core/src/main/kotlin/integration/core/Entities.kt
- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcDeleteSingleReturningTest.kt
- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcUpdateSingleReturningTest.kt
- integration-test-r2dbc/src/test/kotlin/integration/r2dbc/R2dbcDeleteSingleReturningTest.kt
- integration-test-r2dbc/src/test/kotlin/integration/r2dbc/R2dbcUpdateSingleReturningTest.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/runner/EntityUpdateSingleReturningRunner.kt
- komapper-jdbc/src/main/kotlin/org/komapper/jdbc/dsl/runner/JdbcEntityDeleteSingleReturningRunner.kt
- komapper-jdbc/src/main/kotlin/org/komapper/jdbc/dsl/runner/JdbcEntityUpdateSingleReturningRunner.kt
- komapper-r2dbc/src/main/kotlin/org/komapper/r2dbc/dsl/runner/R2dbcEntityDeleteSingleReturningRunner.kt
- komapper-r2dbc/src/main/kotlin/org/komapper/r2dbc/dsl/runner/R2dbcEntityUpdateSingleReturningRunner.kt
This pull request prevents the unintended occurrence of OptimisticLockException.
> Distinguish between a column being null and the absence of a record in a `returning(expression)` query

- integration-test-core/src/main/kotlin/integration/core/Entities.kt
- integration-test-core/src/main/kotlin/integration/core/PostgreSqlSetting.kt
- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcInsertBatchTest.kt
- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcInsertMultipleTest.kt
- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcInsertSingleTest.kt
- komapper-core/src/main/kotlin/org/komapper/core/Dialect.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/builder/BuilderUtility.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/context/EntityInsertContext.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/context/EntityUpsertContext.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/query/InsertQueryBuilder.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/runner/EntityUpsertBatchRunner.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/runner/EntityUpsertMultipleRunner.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/runner/EntityUpsertSingleRunner.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/runner/RunnerUtility.kt
- komapper-dialect-postgresql/src/main/kotlin/org/komapper/dialect/postgresql/PostgreSqlDialect.kt
- komapper-dialect-postgresql/src/main/kotlin/org/komapper/dialect/postgresql/PostgreSqlEntityUpsertStatementBuilder.kt
This PR introduces support for the `ON CONFLICT WHERE` clause in PostgreSQL. The `ON CONFLICT WHERE` clause allows for more granular control over conflict handling by adding conditional constraints during `INSERT` operations, enabling developers to specify when conflicts should be handled based on additional criteria.
Please also refer to the explanation of index_predicate in the PostgreSQL documentation:
https://www.postgresql.org/docs/current/sql-insert.html
```kotlin
val n = Meta.name
val name = Name(1, "first", "last", null)
val query = QueryDsl.insert(n).onDuplicateKeyUpdate(n.lastName) {
n.deletedAt.isNull()
}.single(name)
```
``` sql
insert into names as t0_ (id, first_name, last_name, deleted_at) 
values (1, 'first', 'last', null) 
on conflict (last_name) where deleted_at is null …
```
> Add support for `ON CONFLICT WHERE` in Postgres

- gradle/libs.versions.toml
- komapper-spring-boot-autoconfigure-jdbc/build.gradle.kts
- komapper-spring-boot-autoconfigure-jdbc/src/main/kotlin/org/komapper/spring/boot/autoconfigure/jdbc/KomapperJdbcAutoConfiguration.kt
- komapper-spring-boot-autoconfigure-jdbc/src/test/kotlin/org/komapper/spring/boot/autoconfigure/jdbc/KomapperJdbcAutoConfigurationTest.kt
- komapper-spring-boot-autoconfigure-r2dbc/build.gradle.kts
- komapper-spring-boot-autoconfigure-r2dbc/src/main/kotlin/org/komapper/spring/boot/autoconfigure/r2dbc/KomapperR2dbcAutoConfiguration.kt
- komapper-spring-boot-autoconfigure-r2dbc/src/test/kotlin/org/komapper/spring/boot/autoconfigure/r2dbc/KomapperR2dbcAutoConfigurationTest.kt
Spring Boot provides `ApplicationContextRunner` as a way to properly test autoconfigurations. It matches the way Spring Boot loads configurations by itself, making sure, e.g., that user configuration beans take precedence over autoconfigured ones, autoconfigurations are properly ordered, etc.
Using `ApplicationContextRunner` makes tests more resilient to configuration and better match real behaviour.
See https://spring.io/blog/2018/03/07/testing-auto-configurations-with-spring-boot-2-0 for more details.
Avoid using `@ImportAutoConfiguration` on autoconfiguration classes. That creates rigid dependencies that can become problematic in case when multiple autoconfigurations provide the same bean.
In particular, that causes issues when `KomapperJdbcAutoConfiguration` is used along with Spring …
> Fix SpringBoot autoconfiguration dependencies & polish

- komapper-quarkus-jdbc/src/main/java/org/komapper/quarkus/jdbc/DefaultDataSourceResolver.java
We stop using `io.quarkus.agroal.runtime.DataSources` and switch to `AgroalDataSourceUtil`.
> Avoid the use of deprecated class

- integration-test-core/src/main/kotlin/integration/core/PostgreSqlSetting.kt
- integration-test-r2dbc/src/main/kotlin/integration/r2dbc/EntityDataType.kt
- integration-test-r2dbc/src/postgresql/kotlin/integration/r2dbc/postgresql/R2dbcPostgreSqlMapping.kt
- integration-test-r2dbc/src/test/kotlin/integration/r2dbc/R2dbcDataTypeTest.kt
- komapper-dialect-postgresql-r2dbc/src/main/kotlin/org/komapper/dialect/postgresql/r2dbc/PostgreSqlR2dbcDataTypeProvider.kt
The changes in this pull request address the mapping of arrays such as `Array<Int>` and `Array<Long>` to database types in PostgreSQL R2DBC. This update ensures proper handling of Primitive Boxed Generic Array Types.
> Fix mapping of Primitive Boxed Generic Array Types

- komapper-quarkus-jdbc-deployment/src/main/java/org/komapper/quarkus/jdbc/deployment/KomapperSettingsFactory.java
Enhanced the detection of the appropriate JDBC driver when the `db-kind` property in Quarkus is set to `"oracle"`, `"sqlserver"`, or `"mssql"`.
> Add support for Oracle and SQL Server in Quarkus

- komapper-r2dbc/src/main/kotlin/org/komapper/r2dbc/R2dbcExecutor.kt
We identified an intermittent issue where R2DBC row processing occasionally executed concurrently across multiple threads, resulting in unpredictable ordering of results. This rare but reproducible problem occurred even when using explicit ⁠`ORDER BY` clauses in queries, violating the expected result ordering.
This PR converts Reactor's Flux to Kotlin Flow before collecting results, ensuring single-threaded sequential processing. Specifically, we added `.asFlow()` between `result.map()` and `.collect()` to avoid Flux's concurrent behavior and guarantee ordered processing.
While a more direct approach might be using `.publishOn(Schedulers.single())` for Reactor Flux, the API returns a more generic Reactive Streams Publisher type rather than a concrete Flux, making the Flow conversion …
> fix: Serialize r2dbc row processing by converting Flux to Flow

- integration-test-r2dbc/src/test/kotlin/integration/r2dbc/R2dbcSequentialExecutionTest.kt
Update R2dbcSequentialExecutionTest to remove unnecessary sorting operations.
> Remove unnecessary sorting in R2dbcSequentialExecutionTest

- komapper-core/src/main/kotlin/org/komapper/core/ClockProvider.kt
- komapper-core/src/test/kotlin/org/komapper/core/ClockProviderTest.kt
If the application has a bean of type `Clock` available in the context, pass that through to the `DefaultClockProvider` instead of using `Instant.now()`
This allows easier synchronization (and unit testing) when an application has a clock defined in the context
> Accept a Clock in DefaultDefaultClockProvider's Primary Constructor

- gradle-plugin/src/main/java/org/komapper/gradle/codegen/GenerateTask.java
- gradle-plugin/src/main/java/org/komapper/gradle/codegen/Generator.java
- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcMetadataReaderTest.kt
- komapper-codegen/src/main/java/org/komapper/codegen/CodeGenerator.java
- komapper-codegen/src/main/java/org/komapper/codegen/PackageNameResolver.java
- komapper-codegen/src/main/java/org/komapper/codegen/PackageNameResolverImpl.java
- komapper-codegen/src/test/kotlin/org/komapper/codegen/CodeGeneratorTest.kt
- komapper-codegen/src/test/kotlin/org/komapper/codegen/PackageNameResolverImplTest.kt
Introduce `PackageNameResolver` to handle package names containing reserved keywords like `class` by wrapping them in backticks. Updated `CodeGenerator` and relevant tests to use the new resolver for proper package name handling.
#608 
#609
> Add support for resolving package names with reserved keywords

- .github/labeler.yml
- komapper-quarkus-jdbc/src/main/java/org/komapper/quarkus/jdbc/KomapperRecorder.java
Fixed parameter order in `ExecutionOptions` instantiation by reordering `maxRows` and `fetchSize` to align with the constructor's expected sequence.
> Fix parameter order in quarkus configuration

- komapper-spring-boot-autoconfigure-jdbc/src/main/kotlin/org/komapper/spring/boot/autoconfigure/jdbc/KomapperJdbcAutoConfiguration.kt
- komapper-spring-boot-autoconfigure-jdbc/src/test/kotlin/org/komapper/spring/boot/autoconfigure/jdbc/KomapperJdbcAutoConfigurationTest.kt
- komapper-spring-boot-autoconfigure-r2dbc/src/main/kotlin/org/komapper/spring/boot/autoconfigure/r2dbc/KomapperR2dbcAutoConfiguration.kt
- komapper-spring-boot-autoconfigure-r2dbc/src/test/kotlin/org/komapper/spring/boot/autoconfigure/r2dbc/KomapperR2dbcAutoConfigurationTest.kt
- komapper-spring-boot-test-autoconfigure-jdbc/src/main/resources/META-INF/spring/org.komapper.spring.boot.test.autoconfigure.jdbc.AutoConfigureKomapperJdbc.imports
- komapper-spring-boot-test-autoconfigure-r2dbc/src/main/resources/META-INF/spring/org.komapper.spring.boot.test.autoconfigure.r2dbc.AutoConfigureKomapperR2dbc.imports
Tune the way Komapper Spring Boot integration works with properties, so it could natively work with Spring Boot Testcontainers integration.
For that, Komapper autoconfigurations should read `JdbcConnectionDetails`/`R2dbcConnectionDetails` beans instead of directly reading application properties (although properties can be used as a fallback).
`AutoConfigureKomapperJdbc`/`AutoConfigureKomapperR2dbc` test slices are also updated to optionally load `ServiceConnectionAutoConfiguration` from the `spring-boot-testcontainers` module.
This requires at least Spring Boot 3.1.0.
References:
* https://spring.io/blog/2023/06/19/spring-boot-31-connectiondetails-abstraction
* https://spring.io/blog/2023/06/23/improved-testcontainers-support-in-spring-boot-3-1
* …
> Enhance Komapper Spring Boot Testcontainers integration

- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcInsertMultipleReturningTest.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/query/InsertOnDuplicateKeyIgnoreQueryBuilder.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/query/InsertOnDuplicateKeyUpdateQueryBuilder.kt
because, cannot use returning entity value.
> Fix  `onDuplicateKeyUpdate` and `onDuplicateKeyIgnore` multiple method return type
