- .github/workflows/build.yml
> Revert "Don't publish until the plugin is approved (#65)"

- integration-test-r2dbc/src/test/kotlin/integration/r2dbc/EntityInsertQueryTest.kt
- komapper-r2dbc/src/main/kotlin/org/komapper/r2dbc/R2dbcExecutor.kt
https://github.com/pgjdbc/r2dbc-postgresql/issues/415
> Consume either tabular results or an update count.

- integration-test-jdbc/src/test/kotlin/integration/jdbc/TemplateExecuteQueryTest.kt
- integration-test-jdbc/src/test/kotlin/integration/jdbc/TemplateSelectQueryTest.kt
- integration-test-r2dbc/src/test/kotlin/integration/r2dbc/TemplateExecuteQueryTest.kt
- integration-test-r2dbc/src/test/kotlin/integration/r2dbc/TemplateSelectQueryTest.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/query/TemplateExecuteQuery.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/query/TemplateSelectQueryBuilder.kt
Accept an Any type instead of a function type.
> Change the bind function signature in Template DSL.

- komapper-jdbc/src/main/kotlin/org/komapper/jdbc/JdbcExecutor.kt
- komapper-r2dbc/src/main/kotlin/org/komapper/r2dbc/R2dbcExecutor.kt
See also https://kt.academy/article/ek-member-extensions
> Avoid member extensions

- komapper-processor/src/main/kotlin/org/komapper/processor/EntityDefinitionSourceResolver.kt
- komapper-processor/src/test/kotlin/org/komapper/processor/EntityProcessorTest.kt
Make it easier to see where the problem occurred, even if the entity class is not included in the user's project.
> Improve error messages from KSP.

- komapper-tx-jdbc/src/main/kotlin/org/komapper/tx/jdbc/TransactionScope.kt
- komapper-tx-jdbc/src/main/kotlin/org/komapper/tx/jdbc/utility.kt
- komapper-tx-r2dbc/src/main/kotlin/org/komapper/tx/r2dbc/TransactionScope.kt
- komapper-tx-r2dbc/src/main/kotlin/org/komapper/tx/r2dbc/utility.kt
This class is needed to execute non-transactional logic in the test environment.
> Add the TransactionScopeStub class.

- .github/workflows/build.yml
- .github/workflows/release.yml
- build.gradle.kts
- example-spring-boot-jdbc/build.gradle.kts
- example-spring-boot-r2dbc/build.gradle.kts
- gradle.properties
- komapper-jdbc/src/main/kotlin/org/komapper/jdbc/JdbcDatabaseConfig.kt
- komapper-spring-boot-autoconfigure-jdbc/src/main/kotlin/org/komapper/spring/boot/autoconfigure/jdbc/KomapperAutoConfiguration.kt
- komapper-spring-boot-starter-jdbc/build.gradle.kts
- komapper-spring-boot-starter-r2dbc/build.gradle.kts
- komapper-spring-native-jdbc/build.gradle.kts
- komapper-spring-native-jdbc/src/main/kotlin/org/komapper/spring/nativex/jdbc/KomapperHints.kt
- komapper-spring-native-jdbc/src/main/resources/META-INF/spring.factories
- settings.gradle.kts
Currently, only the JDBC API is supported.
> Support Spring Native experimentally

- komapper-processor/src/main/kotlin/org/komapper/processor/EntityFactory.kt
- komapper-processor/src/test/kotlin/org/komapper/processor/EntityProcessorTest.kt
> Ignore properties

- komapper-core/src/main/kotlin/org/komapper/core/dsl/query/QueryUtility_composition.kt
See also https://slack-chats.kotlinlang.org/t/8131683/require-returns-an-illegalargumentexception
> Fix incorrect kdoc comment

- integration-test-core/src/main/kotlin/integration/core/H2Setting.kt
- integration-test-core/src/main/kotlin/integration/core/MariaDbSetting.kt
- integration-test-core/src/main/kotlin/integration/core/MySqlSetting.kt
- integration-test-core/src/main/kotlin/integration/core/OracleSetting.kt
- integration-test-core/src/main/kotlin/integration/core/PostgreSqlSetting.kt
- integration-test-core/src/main/kotlin/integration/core/SqlServerSetting.kt
- integration-test-core/src/main/kotlin/integration/core/entities_dataType.kt
- integration-test-core/src/main/kotlin/integration/core/enumclass/Color.kt
- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcDataTypeTest.kt
- integration-test-r2dbc/src/test/kotlin/integration/r2dbc/R2dbcDataTypeTest.kt
- komapper-annotation/src/main/kotlin/org/komapper/annotation/EnumType.kt
- komapper-annotation/src/main/kotlin/org/komapper/annotation/annotations.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/AnnotationSupport.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/Config.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/EntityFactory.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/EntityMetamodelGenerator.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/Symbols.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/data.kt
- komapper-processor/src/test/kotlin/org/komapper/processor/ConfigTest.kt
- komapper-processor/src/test/kotlin/org/komapper/processor/EntityProcessorErrorTest.kt
Here is a sample code:
```kotlin
enum class Color(val code: Int, val abbr: String) {
RED(10, "r"), BLUE(20, "b"), GREEN(30, "g")
}
data class Box(
@KomapperId
val id: Int,
// map Color.code to database
@KomapperEnum(EnumType.PROPERTY, hint = "code")
val value: Color?
)
```
> Support for mapping of arbitrary property of enum class

- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcOperatorTest.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/expression/MathematicalFunction.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/operator/MathematicalFunctions.kt
> Make Random class a data class

- gradle-plugin/src/main/java/org/komapper/gradle/codegen/GenerateTask.java
- gradle-plugin/src/main/java/org/komapper/gradle/codegen/Generator.java
- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcMetadataReaderTest.kt
- komapper-codegen/src/main/java/org/komapper/codegen/CodeGenerator.java
- komapper-codegen/src/test/kotlin/org/komapper/codegen/CodeGeneratorTest.kt
Thank you for your great software.
Now, I would like to add "self-mapping" support to the code generator and have implemented it.
If you don't mind, I would like to have this PR merged into the repository.
> Support Self-mapping in code generator

- integration-test-jdbc/src/h2/kotlin/integration/jdbc/h2/JdbcH2Mapping.kt
- integration-test-jdbc/src/mariadb/kotlin/integration/jdbc/mariadb/JdbcMariaDbMapping.kt
- integration-test-jdbc/src/oracle/kotlin/integration/jdbc/oracle/JdbcOracleMapping.kt
- integration-test-jdbc/src/postgresql/kotlin/integration/jdbc/postgresql/JdbcPostgreSqlMapping.kt
- integration-test-jdbc/src/sqlserver/kotlin/integration/jdbc/sqlserver/JdbcSqlServerMapping.kt
- integration-test-r2dbc/src/h2/kotlin/integration/r2dbc/h2/R2dbcH2Mapping.kt
- integration-test-r2dbc/src/mariadb/kotlin/integration/r2dbc/mariadb/R2dbcMariadbMapping.kt
- integration-test-r2dbc/src/mariadb/kotlin/integration/r2dbc/mariadb/R2dbcMariadbMappingTest.kt
- integration-test-r2dbc/src/mysql/kotlin/integration/r2dbc/mysql/R2dbcMysqlMapping.kt
- integration-test-r2dbc/src/mysql/kotlin/integration/r2dbc/mysql/R2dbcMysqlMappingTest.kt
- integration-test-r2dbc/src/postgresql/kotlin/integration/r2dbc/postgresql/R2dbcPostgreSqlMapping.kt
- integration-test-r2dbc/src/sqlserver/kotlin/integration/r2dbc/sqlserver/R2dbcSqlServerMapping.kt
- komapper-dialect-mariadb-r2dbc/src/main/kotlin/org/komapper/dialect/mariadb/r2dbc/MariaDbR2dbcDataTypeProvider.kt
- komapper-dialect-mysql-r2dbc/src/main/kotlin/org/komapper/dialect/mysql/r2dbc/MySqlR2dbcDataTypeProvider.kt
- komapper-dialect-oracle-jdbc/src/main/kotlin/org/komapper/dialect/oracle/jdbc/OracleJdbcDataTypeProvider.kt
- komapper-dialect-oracle-r2dbc/src/main/kotlin/org/komapper/dialect/oracle/r2dbc/OracleR2dbcDataTypeProvider.kt
Correct the following dialects:
- Jdbc Oracle
- R2dbc MariaDB
- R2dbc MySQL
- R2dbc Oracle
See https://github.com/komapper/komapper/discussions/1035
> Fix ByteArray mapping in create statement

- .github/workflows/build.yml
- .github/workflows/release.yml
Suppress the following alerts:
- https://github.com/komapper/komapper/security/dependabot/1
- https://github.com/komapper/komapper/security/dependabot/2
> Suppress dependabot security alerts

- .github/workflows/build.yml
- .github/workflows/release.yml
Reverts komapper/komapper#1084
> Revert "Update gradle/gradle-build-action action to v2.9.0"

- integration-test-core/src/main/kotlin/integration/core/one/MyTestModel.kt
- integration-test-core/src/main/kotlin/integration/core/two/AnotherModel.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/EntityMetamodelGenerator.kt
> Fix an error that occurred while associating an object from another package

- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcSelectWhereTest.kt
- komapper-core/src/main/kotlin/org/komapper/core/type/ClobString.kt
- komapper-processor/src/main/kotlin/org/komapper/processor/AnnotationSupport.kt
> Fix issue with ClobString not supporting the LIKE operator

- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcOperatorTest.kt
- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcSelectWindowFunctionTest.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/expression/ColumnExpression.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/scope/FilterScope.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/scope/FilterScopeSupport.kt
This Pull Request facilitates comparison between numerical expressions of different types.
> Add operators for Number expressions

- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcSelectAggregateTest.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/builder/BuilderSupport.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/expression/ScalarExpression.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/operator/AliasExpression.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/operator/ArithmeticOperators.kt
Add following operators for scalar expressions:
- `+`
- `-`
- `*`
- `/`
- `%`
- `alias`
The result of the above operators is a scalar expression.
> Add operators for scalar expressions

- komapper-dialect-h2-jdbc/src/main/kotlin/org/komapper/dialect/h2/jdbc/H2JdbcDataTypeProvider.kt
- komapper-dialect-h2-r2dbc/src/main/kotlin/org/komapper/dialect/h2/r2dbc/H2R2dbcDataTypeProvider.kt
> Modify the H2 Database Dialect to ensure BigDecimal is mapped to numeric

- komapper-template/src/main/kotlin/org/komapper/template/TwoWayTemplateStatementBuilder.kt
- komapper-template/src/main/kotlin/org/komapper/template/sql/SqlNode.kt
- komapper-template/src/main/kotlin/org/komapper/template/sql/SqlParser.kt
- komapper-template/src/test/kotlin/org/komapper/template/TwoWayTemplateStatementBuilderTest.kt
> Handle multiple 'union' keywords in SQL templates

- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcSelectAggregateTest.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/builder/BuilderSupport.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/expression/DistinctExpression.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/operator/AggregateFunctions.kt
**Kotlin**
```kotlin
val count = db.runQuery {
QueryDsl.from(e).select(countDistinct(e.managerId))
}
```
**SQL**
```sql
select count(distinct t0_.manager_id) from employee as t0_
```
> Add the countDistinct function

- komapper-tx-jdbc/src/main/kotlin/org/komapper/tx/jdbc/JdbcTransactionConnection.kt
This PR reduces the possibility of pinning in AWS RDS Proxy.
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/rds-proxy-managing.html#rds-proxy-pinning
> Minimize the method calls for Connection

- komapper-processor/src/main/kotlin/org/komapper/processor/command/ExprValidator.kt
- komapper-processor/src/test/kotlin/org/komapper/processor/command/ExprValidatorTest.kt
This pull request allows access to the properties of the Enum class during compile-time.
For example, you can access the `value` property of the following `MyEnum` class.
```kotlin
enum class MyEnum(val value: String) {
A("a"), B("b"), C("c")
}
```
```kotlin
@KomapperCommand("select name from x where myEnum = /* myEnum.value */")
class SelectByMyEnum(val myEnum: MyEnum): Many<String>( { select { it.stringNotNull(0) } } )
```
> Modify to recognize properties of the Enum class during compile-time expression validation

- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcDeleteBatchTest.kt
- integration-test-jdbc/src/test/kotlin/integration/jdbc/JdbcUpdateBatchTest.kt
- integration-test-r2dbc/src/test/kotlin/integration/r2dbc/R2dbcDeleteBatchTest.kt
- integration-test-r2dbc/src/test/kotlin/integration/r2dbc/R2dbcUpdateBatchTest.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/runner/EntityDeleteRunnerSupport.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/runner/EntityUpdateRunnerSupport.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/runner/EntityUpdateSingleReturningRunner.kt
- komapper-core/src/main/kotlin/org/komapper/core/dsl/runner/RunnerUtility.kt
This PR adds entity details to the optimistic lock error message.
> Improve the error message for `OptimisticLockException`

- komapper-core/src/main/kotlin/org/komapper/core/DatabaseConfig.kt
- komapper-core/src/main/kotlin/org/komapper/core/StatisticManager.kt
- komapper-core/src/main/kotlin/org/komapper/core/StatisticManagers.kt
- komapper-core/src/main/kotlin/org/komapper/core/spi/StatisticManagerFactory.kt
- komapper-core/src/test/kotlin/org/komapper/core/StatisticManagersTest.kt
- komapper-quarkus-jdbc-deployment/src/main/java/org/komapper/quarkus/jdbc/deployment/KomapperProcessor.java
- komapper-quarkus-jdbc/src/main/java/org/komapper/quarkus/jdbc/KomapperProducer.java
- komapper-spring-boot-autoconfigure-jdbc/src/main/kotlin/org/komapper/spring/boot/autoconfigure/jdbc/KomapperJdbcAutoConfiguration.kt
- komapper-spring-boot-autoconfigure-r2dbc/src/main/kotlin/org/komapper/spring/boot/autoconfigure/r2dbc/KomapperR2dbcAutoConfiguration.kt
The pull request refactors the initialization of StatisticManager by centralizing creation through a provider and introducing extensibility with a new SPI interface. Updated tests and configurations to accommodate the changes.
> Refactor StatisticManager initialization

- komapper-spring-boot-autoconfigure-jdbc/src/main/kotlin/org/komapper/spring/boot/autoconfigure/jdbc/ConditionalOnAnyJdbcDataTypeBean.kt
- komapper-spring-boot-autoconfigure-jdbc/src/main/kotlin/org/komapper/spring/boot/autoconfigure/jdbc/KomapperJdbcAutoConfiguration.kt
- komapper-spring-boot-autoconfigure-jdbc/src/test/kotlin/org/komapper/spring/boot/autoconfigure/jdbc/KomapperJdbcAutoConfigurationTest.kt
- komapper-spring-boot-autoconfigure-r2dbc/src/main/kotlin/org/komapper/spring/boot/autoconfigure/r2dbc/ConditionalOnAnyR2dbcDataTypeBean.kt
- komapper-spring-boot-autoconfigure-r2dbc/src/main/kotlin/org/komapper/spring/boot/autoconfigure/r2dbc/KomapperR2dbcAutoConfiguration.kt
- komapper-spring-boot-autoconfigure-r2dbc/src/test/kotlin/org/komapper/spring/boot/autoconfigure/r2dbc/KomapperR2dbcAutoConfigurationTest.kt
In addition to *DataType beans being autodetected in #1478, autodetect *UserDefinedDataType beans
> Spring Boot: also detect UserDefined *DataType beans

- integration-test-r2dbc/src/test/kotlin/integration/r2dbc/R2dbcSequentialExecutionTest.kt
- komapper-r2dbc/src/main/kotlin/org/komapper/r2dbc/R2dbcExecutor.kt
- komapper-spring-r2dbc/src/main/kotlin/org/komapper/spring/r2dbc/SpringR2dbcTransactionSession.kt
Update the code to use `kotlinx.coroutines.reactive.asFlow` in place of `kotlinx.coroutines.reactive.collect` to ensure sequential execution.
> Use `kotlinx.coroutines.reactive.asFlow` instead of `kotlinx.coroutines.reactive.collect`

- .github/workflows/release.yml
Refactored the release version retrieval process in the workflow for improved efficiency and readability.
> Refactor release version retrieval in workflow

- .github/workflows/release.yml
Update RELEASE_VERSION assignment in release workflow to correct value.
> Fix RELEASE_VERSION assignment in release workflow

- komapper-quarkus-jdbc-deployment/src/main/java/org/komapper/quarkus/jdbc/deployment/KomapperBuildTimeConfig.java
- komapper-quarkus-jdbc-deployment/src/main/java/org/komapper/quarkus/jdbc/deployment/KomapperSettingsFactory.java
Refactor Komapper configuration to use SmallRye ConfigMapping for improved clarity and maintainability. 
See https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.14#for-extension-developers.
> Convert the configuration to @ConfigMapping
